name: Build

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Set Gradle Wrapper permission
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Set Gradle Wrapper permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Last-Summer-Project' && github.ref == 'refs/heads/master' }}
    needs: test
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Set Gradle Wrapper permission
        run: chmod +x ./gradlew

      - name: Build docker image (for master)
        run: ./gradlew bootBuildImage
        env:
          CONTAINER_IMAGE_NAME: ${{ github.repository }}
          CONTAINER_REGISTRY_URL: "ghcr.io"
          CONTAINER_REGISTRY_USERNAME: ${{ github.repository_owner }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
